export enum SyllabusesPermission {
  CREATE_SYLLABUSES = 'CREATE_SYLLABUSES',
  UPDATE_SYLLABUSES = 'UPDATE_SYLLABUSES',
  DELETE_SYLLABUSES = 'DELETE_SYLLABUSES',
  GET_SYLLABUSES = 'GET_SYLLABUSES',
  GET_LIST_SYLLABUSES = 'GET_LIST_SYLLABUSES',
}
